apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftapp
  namespace: sn-labs-osamaalmraya
  labels:
    app: giftapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giftapp
  template:
    metadata:
      labels:
        app: giftapp
    spec:
      containers:
      - name: giftapp-container
        image: us.icr.io/sn-labs-osamaalmraya/giftapp:latest
        ports:
        - containerPort: 3060
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000               # run as non-root UID
          capabilities:
            drop:
              - "ALL"
          seccompProfile:
            type: RuntimeDefault
      imagePullSecrets:
        - name: icr

---
apiVersion: v1
kind: Service
metadata:
  name: gift-app-service
  namespace: sn-labs-osamaalmraya
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3060
    protocol: TCP
  selector:
    app: giftapp
